# NumPy

NumPy is a Python library for numerical computing that provides high-performance multidimensional arrays and is implemented primarily in C for efficient execution.

In [108]:
import numpy as np

## Array

Linear data structure

In [109]:
lst = [i for i in range(1, 6)]
arr = np.array(lst)
type(arr)

numpy.ndarray

In [110]:
arr

array([1, 2, 3, 4, 5])

In [111]:
print(arr.shape)
print(arr)

(5,)
[1 2 3 4 5]


## Multi-nested Array

Array of arrays

In [112]:
lst1 = [i for i in range(6, 11)]
lst2 = [i**2 for i in range(6, 11)]
lst3 = [i**3 for i in range(6, 11)]

mat = np.array([lst1, lst2, lst3])
type(mat)

numpy.ndarray

In [113]:
mat

array([[   6,    7,    8,    9,   10],
       [  36,   49,   64,   81,  100],
       [ 216,  343,  512,  729, 1000]])

In [114]:
print(mat.shape)
print(mat)

(3, 5)
[[   6    7    8    9   10]
 [  36   49   64   81  100]
 [ 216  343  512  729 1000]]


## Reshape

The product of input rows and columns must be equal to the number of elements in the original array

In [115]:
mat1 = mat.reshape(5, 3)
mat1

array([[   6,    7,    8],
       [   9,   10,   36],
       [  49,   64,   81],
       [ 100,  216,  343],
       [ 512,  729, 1000]])

In [116]:
mat1.shape

(5, 3)

## Indexing & Slicing

Accessing array elements

In [117]:
arr[3]

np.int64(4)

In [118]:
arr[1:3]

array([2, 3])

In [119]:
arr[2:]

array([3, 4, 5])

In [120]:
arr[::-1]

array([5, 4, 3, 2, 1])

Accessing matrix (2-D array) elements

In [121]:
mat[0]

array([ 6,  7,  8,  9, 10])

In [122]:
mat[1:][3:]

array([], shape=(0, 5), dtype=int64)

In [123]:
mat[1:, 2:4]

array([[ 64,  81],
       [512, 729]])

## Copying Array

Broadcasting

In [124]:
print(arr)
arr[2:] = 100
print(arr)

[1 2 3 4 5]
[  1   2 100 100 100]


Deep copy (Array is a reference type)

In [125]:
arr1 = arr
arr1[3:] = 500
print(arr1)
print(arr)

[  1   2 100 500 500]
[  1   2 100 500 500]


Shallow copy

In [126]:
arr2 = arr.copy()
arr2[3:] = 999
print(arr2)
print(arr)

[  1   2 100 999 999]
[  1   2 100 500 500]


## In-built Functions

### arange()

In [127]:
lst1to10 = np.arange(1, 10)
lst1to10

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
lst1to10step2 = np.arange(1, 10, 3)
lst1to10step2

array([1, 4, 7])

### linspace()

In [129]:
linSpace = np.linspace(1, 10, 25)
linSpace

array([ 1.   ,  1.375,  1.75 ,  2.125,  2.5  ,  2.875,  3.25 ,  3.625,
        4.   ,  4.375,  4.75 ,  5.125,  5.5  ,  5.875,  6.25 ,  6.625,
        7.   ,  7.375,  7.75 ,  8.125,  8.5  ,  8.875,  9.25 ,  9.625,
       10.   ])

### ones()

In [130]:
ones1 = np.ones(4)
ones1

array([1., 1., 1., 1.])

In [131]:
ones2 = np.ones((2, 5), dtype=int)
ones2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### rand()
Random distribution over [0, 1)

In [132]:
rd = np.random.rand(3, 3)
rd

array([[0.04122625, 0.33933509, 0.76187269],
       [0.80506564, 0.379054  , 0.77560465],
       [0.30802835, 0.37670156, 0.75384835]])

### randn()
Standard Normal distribution

In [133]:
snd = np.random.randn(2, 4)
snd

array([[ 0.46959853, -0.35391298, -1.13883301, -0.3268642 ],
       [ 0.90696958,  0.08231302,  0.17196382, -0.4471726 ]])

### randint()

In [134]:
rint = np.random.randint(1, 100, 15).reshape(3, 5)
rint

array([[85, 96, 42, 55, 54],
       [87, 54, 79, 45, 72],
       [70, 94, 11, 95, 19]], dtype=int32)

### random_sample()

Same as rand(), but takes array shape as a tuple input

In [135]:
rsamp = np.random.random_sample((2, 3))
rsamp

array([[0.18944486, 0.8642481 , 0.7231709 ],
       [0.08505089, 0.37965896, 0.21709559]])

## Array Conditioning

In [136]:
lst1to10 < 4

array([ True,  True,  True, False, False, False, False, False, False])

In [137]:
lst1to10[lst1to10 < 4]

array([1, 2, 3])

In [138]:
lst1to10 * 7

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63])